import { StyleSheet, Platform } from 'react-native';
import { C, F } from './theme';

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  content: { padding: 16, paddingBottom: 32 },
  topbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  logoRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  logoText: { fontFamily: F.bold, color: C.navy, letterSpacing: -0.5 },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  logoutText: { fontFamily: F.semi, fontSize: 13, color: C.muted },

  /* --- Autenticação --- */
  authScroll: { flexGrow: 1, justifyContent: 'center', padding: 20 },
  authCard: {
    width: '100%',
    maxWidth: 460,
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 28,
    paddingVertical: 40,
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  authTitle: {
    fontFamily: F.bold,
    fontSize: 24,
    color: '#1E293B',
    textAlign: 'center',
    marginTop: 32,
    letterSpacing: -0.4,
  },
  authSubtitle: {
    fontFamily: F.regular,
    fontSize: 14,
    color: C.muted,
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 8,
  },
  authLabel: { fontFamily: F.semi, fontSize: 13, color: '#1E293B' },
  authLink: { fontFamily: F.semi, fontSize: 13, color: C.blueMid },
  authInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    height: 52,
    marginTop: 8,
    paddingHorizontal: 14,
    backgroundColor: C.inputBg,
    borderRadius: 12,
  },
  authInput: {
    flex: 1,
    height: '100%',
    fontFamily: F.regular,
    fontSize: 15,
    color: C.text,
    ...Platform.select({ web: { outlineStyle: 'none' }, default: {} }),
  },
  authBtn: {
    height: 54,
    marginTop: 26,
    backgroundColor: C.blueMid,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: C.blueMid,
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  authBtnText: { fontFamily: F.bold, fontSize: 16, color: '#fff' },
  authDivider: {
    height: 1,
    backgroundColor: C.border,
    marginTop: 32,
    marginBottom: 22,
  },
  authFooter: {
    fontFamily: F.regular,
    fontSize: 14,
    color: C.muted,
    textAlign: 'center',
  },
  authFooterLink: { fontFamily: F.semi, color: C.blueMid },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 18,
    padding: 12,
    backgroundColor: C.redBg,
    borderRadius: 10,
  },
  errorText: { flex: 1, fontFamily: F.medium, fontSize: 13, color: C.red },

  eyebrow: {
    fontFamily: F.bold,
    fontSize: 11,
    color: C.blue,
    letterSpacing: 1,
  },
  title: { fontFamily: F.black, fontSize: 26, color: C.text, marginTop: 2 },
  subtitle: {
    fontFamily: F.regular,
    fontSize: 13,
    color: C.muted,
    marginTop: 4,
  },

  card: {
    backgroundColor: C.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.border,
    padding: 16,
    marginBottom: 12,
  },
  cardTitle: {
    fontFamily: F.bold,
    fontSize: 16,
    color: C.text,
    marginBottom: 2,
  },
  kpiLabel: {
    fontFamily: F.bold,
    fontSize: 10,
    color: C.muted,
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  kpiValue: { fontFamily: F.black, fontSize: 24, color: C.text },
  body: { fontFamily: F.regular, fontSize: 13, color: C.text },
  bodyBold: { fontFamily: F.semi, fontSize: 13, color: C.text },
  small: { fontFamily: F.regular, fontSize: 12, color: C.muted, marginTop: 2 },
  link: { fontFamily: F.semi, fontSize: 12, color: C.blue },
  label: {
    fontFamily: F.semi,
    fontSize: 12,
    color: C.text,
    marginTop: 12,
    marginBottom: 6,
  },

  grid2: { flexDirection: 'row', flexWrap: 'wrap', marginHorizontal: -6 },
  half: { width: '50%', paddingHorizontal: 6 },

  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
  },
  rowGap: { flexDirection: 'row', gap: 10, marginTop: 4 },
  divider: { height: 1, backgroundColor: C.border, marginVertical: 12 },
  dividedItem: {
    borderTopWidth: 1,
    borderTopColor: C.border,
    marginTop: 10,
    paddingTop: 10,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: C.border,
    marginTop: 4,
  },

  badge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 20 },
  badgeText: { fontFamily: F.semi, fontSize: 11 },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontFamily: F.bold, fontSize: 12, color: C.navy },
  rank: {
    width: 24,
    height: 24,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rankText: { fontFamily: F.bold, fontSize: 11, color: '#fff' },

  alertBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
  },
  insight: {
    backgroundColor: '#EFF6FF',
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
  },
  insightText: {
    fontFamily: F.regular,
    fontSize: 12,
    color: C.muted,
    lineHeight: 18,
  },

  chart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 140,
    marginTop: 14,
  },
  chartCol: { flex: 1, alignItems: 'center' },
  chartBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
    height: 100,
  },
  bar: { width: 9, borderRadius: 3 },
  chartLabel: {
    fontFamily: F.regular,
    fontSize: 10,
    color: C.muted,
    marginTop: 6,
  },

  stack: {
    flexDirection: 'row',
    height: 14,
    borderRadius: 7,
    overflow: 'hidden',
    marginVertical: 14,
  },
  legendRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 4 },
  dot: { width: 8, height: 8, borderRadius: 4, marginRight: 8 },
  progressRow: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  track: {
    flex: 1,
    height: 22,
    backgroundColor: '#F1F5F9',
    borderRadius: 11,
    overflow: 'hidden',
  },
  fill: {
    height: 22,
    backgroundColor: C.navy,
    borderRadius: 11,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: 8,
    minWidth: 30,
  },
  fillText: { fontFamily: F.bold, fontSize: 10, color: '#fff' },

  input: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: F.regular,
    fontSize: 13,
    color: C.text,
  },
  dashedBtn: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: C.bluePale,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  softBtn: {
    backgroundColor: '#EFF6FF',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chip: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
  },
  summary: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    padding: 14,
    marginTop: 16,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: C.bluePale,
  },

  primaryBtn: {
    backgroundColor: C.blue,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 12,
  },
  darkBtn: {
    backgroundColor: C.navy,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  primaryBtnText: { fontFamily: F.bold, fontSize: 14, color: '#fff' },
  btnDisabled: { backgroundColor: '#B6C4D8' },

  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
  },
  sizeBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    padding: 8,
    marginTop: 8,
  },
  selected: { borderColor: C.blue, backgroundColor: '#EFF6FF' },
  preview: {
    height: 110,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: C.bluePale,
    backgroundColor: '#F8FAFC',
    marginBottom: 12,
  },
  empty: {
    height: 90,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: C.border,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 12,
  },

  tabbar: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: C.border,
    paddingHorizontal: 6,
    paddingVertical: 8,
  },
  tab: { flex: 1, alignItems: 'center', paddingVertical: 8, borderRadius: 10 },
  tabActive: { backgroundColor: '#EFF6FF' },
  tabText: { fontFamily: F.medium, fontSize: 11, color: C.muted },
});

export default s;
